application:
  subdomain: rss-translator
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://rsstranslator:8000/

services:
  rsstranslator:
    # upstream: docker.io/versun/rssbox:2025.9.18
    image: registry.lazycat.cloud/czyt/versun/rssbox:0651b2ed8e7b5f9c
    environment:
      - SITE_URL=https://${LAZYCAT_APP_DOMAIN}
      - REDIS_URL=redis://rssbox_redis:6379/0
      - CSRF_TRUSTED_ORIGINS=https://${LAZYCAT_APP_DOMAIN}
      - DEFAULT_TARGET_LANGUAGE="Chinese Simplified"
      - PORT=8000
      - DEBUG=0
      - DEMO=0
      - USER_MANAGEMENT=0
      - LOG_LEVEL=ERROR
      - default_max_posts=20
    binds:
      - /lzcapp/var/data:/app/data
    depends_on:
      - rssbox_redis

  rssbox_redis:
    # upstream: docker.io/library/redis:latest
    image: registry.lazycat.cloud/edward/library/redis:4c6b9d7b7a334a2e
    binds:
      - /lzcapp/var/redis:/data
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping
      interval: 30s
